---

- name: delete ArgoCD namespace
  kubernetes.core.k8s:
    kubeconfig:         "{{ argocd_kubeconfig }}"
    name:               "monitoring"
    api_version:        v1
    kind:               Namespace
    state:              absent
    wait:               yes
  when:                 argocd_reset == true


- name: add ArgoCD app Prometheus yamls
  kubernetes.core.k8s:
    kubeconfig:                 "{{ argocd_kubeconfig }}"
    state:                      "{{ argocd_deployment_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   argocd-prometheus-yaml
      spec:
        project:                default
        source:
          repoURL:              https://github.com/OlafRadicke/own_dog_food.git
          targetRevision:       feature/prometheus_rules
          path:                 argocd/prometheus
        destination:
          server:               "https://kubernetes.default.svc"
          namespace:            argocd
        automated:
          prune: true

- name: add ArgoCD app Prometheus helm chart
  kubernetes.core.k8s:
    kubeconfig:                 "{{ argocd_kubeconfig }}"
    state:                      "{{ argocd_deployment_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   prometheus
        namespace:              "{{ argocd_namespace }}"
      spec:
        project:                default
        source:
          chart:                prometheus
          repoURL:              https://prometheus-community.github.io/helm-charts
          targetRevision:       15.9.1
          helm:
            releaseName:        prometheus
            # valueFiles:
            #   - https://github.com/bla/values.yaml
        destination:
          server:               "https://kubernetes.default.svc"
          namespace:            monitoring
