---



# # ArgoCD workflow manifest
# - name:                 download ArgoCD workflow manifest
#   ansible.builtin.get_url:
#     url:                https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/install.yaml
#     dest:               /tmp/argocd-workflow-install.yaml
#     mode:               '0664'

# - name:                 apply ArgoCD workflow manifest
#   kubernetes.core.k8s:
#     kubeconfig:         "{{ argocd_kubeconfig }}"
#     state:              "{{ argocd_deployment_state }}"
#     namespace:          "{{ argocd_namespace }}"
#     wait:               yes
#     src:                /tmp/argocd-workflow-install.yaml

- name:                         add ArgoCD workflow helm chart
  kubernetes.core.k8s:
    kubeconfig:                 "{{ argocd_kubeconfig }}"
    state:                      "{{ argocd_deployment_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   argocd-workflow
        namespace:              "{{ argocd_namespace }}"
      spec:
        project:                default
        syncPolicy:
          automated:
            prune:              true
          syncOptions:
          -                     PruneLast=true
          -                     Replace=true
        destination:
          server:               https://kubernetes.default.svc
          namespace:            argocd
        source:
          chart:                argo-workflows
          repoURL:              https://charts.bitnami.com/bitnami
          targetRevision:       2.3.4 
          helm:
            server:
              auth:
                enabled: false


- name: add ArgoCD workflow routing
  kubernetes.core.k8s:
    kubeconfig:                 "{{ argocd_kubeconfig }}"
    state:                      "{{ argocd_deployment_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   workflow-routes
        namespace:              "{{ argocd_namespace }}"
      spec:
        project:                default
        syncPolicy:
          automated:
            prune:              true
          syncOptions:
          -                     PruneLast=true
          -                     Replace=true
        destination:
          server:               "https://kubernetes.default.svc"
          namespace:            argocd
        source:
          chart:                mutual_tls
          repoURL:              https://olafradicke.github.io/own_dog_food/helm/charts/
          targetRevision:       0.1.5
          helm:
            values: |
                                app:
                                  name: workflow
                                  fqdn: workflow.olaf-radicke.de
                                  service: argocd-workflow-argo-workflows-server
                                secretnames: mtls-ca


- name:                 add ArgoCD workflow example
  kubernetes.core.k8s:
    kubeconfig:         "{{ argocd_kubeconfig }}"
    state:              "{{ argocd_deployment_state }}"
    namespace:          "{{ argocd_namespace }}"
    wait:               yes
    definition:
      apiVersion:       argoproj.io/v1alpha1
      kind:             Workflow
      metadata:
        generateName:   hello-world-
        labels:
          workflows.argoproj.io/archive-strategy: "false"
        annotations:
          workflows.argoproj.io/description: |
                        This is a simple hello world example.
                        You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
      spec:
        entrypoint:     whalesay
        templates:
        - name:         whalesay
          container:
            image:      docker/whalesay:latest
            command:    [cowsay]
            args:       ["hello world"]