
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: opentofu-backend
#   annotations:
#     argocd.argoproj.io/sync-wave: "3"
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 300Mi
#   storageClassName: manual-sc
#   volumeName: manual-pv

Unable to delete application: error patching application with finalizers: Application.argoproj.io "workflows-opentofu" is invalid: metadata.finalizers: Forbidden: no new finalizers can be added if the object is being deleted, found new finalizers []string{"resources-finalizer.argocd.argoproj.io/foreground"}