apiVersion:         argoproj.io/v1alpha1
kind:               WorkflowTemplate
metadata:
  name:             vault-operation
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  templates:

    - name:         get-vault-sleep
      container:
        image:      docker.io/olafradicke/alpine-vault:0.7.4-ci
        env:
        - name:     VAULT_ADDR
          value:    "{{workflow.parameters.terraformCodePath}}"
        - name:     VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key:  token
        command:    ["sh"]
        args:       ["sleep", "1200"]
        workingDir: /

    - name:         get-vault-status
      container:
        image:      docker.io/olafradicke/alpine-vault:0.7.4-ci
        env:
        - name:     VAULT_ADDR
          value:    "{{workflow.parameters.terraformCodePath}}"
        - name:     VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key:  token
        args:       ["status"]
        workingDir: /

    - name:         enable-transit
      container:
        image:      docker.io/olafradicke/alpine-vault:0.7.4-ci
        env:
        - name:     VAULT_ADDR
          value:    "{{workflow.parameters.terraformCodePath}}"
        - name:     VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key:  token
        command:    ["vault"]
        args:
                    - "secrets"
                    - "enable"
                    - "-path=sops"
                    - "transit"
                    - "|"
                    - "true"
        workingDir: /src/clone/terraform/examples
        volumeMounts:
        - name:     argo-workdir
          mountPath: /src


    - name:         create-key
      container:
        image:      docker.io/olafradicke/alpine-vault:0.7.4-ci
        env:
        - name:     VAULT_ADDR
          value:    "{{workflow.parameters.terraformCodePath}}"
        - name:     VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              name: vault-token
              key:  token
        args:
                    - "write"
                    - "sops/keys/default"
                    - "type=rsa-4096"
        workingDir: /src/clone/terraform/examples
        volumeMounts:
        - name:     argo-workdir
          mountPath: /src