---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quaker-kr-de
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: quaker-kr-de
  sources:
    - path: argocd-app-of-apps/cluster/irish-sea/quaker-kr-de/manifests
      repoURL: https://github.com/OlafRadicke/own_dog_food.git
      targetRevision: HEAD
      directory:
        recurse: true

  destination:
    namespace: quaker-kr-de
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
