apiVersion: v1
entries:
  tekton:
  - apiVersion: v2
    appVersion: 0.37.2
    created: "2022-07-30T10:04:17.803836084+02:00"
    description: A Helm chart for Kubernete
    digest: a2ff0e28749db7e0537bfa88e82d831df0324b9dd3b8dd3fe74dc2fb13af51d8
    name: tekton
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tekton-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 0.37.2-latest
    created: "2022-07-30T10:04:17.803354353+02:00"
    description: A Helm chart for Kubernetes
    digest: e5fcd2b05a21aeb431ba745349749c62a6906133aa43ffa7683b21b132416991
    name: tekton
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tekton-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.37.2
    created: "2022-07-30T10:04:17.802625101+02:00"
    description: A Helm chart for Kubernetes
    digest: 6d940f10a17b7848ab21626976313a5af6efe3a992c23a50684973a48b3ab4b1
    name: tekton
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tekton-0.0.1.tgz
    version: 0.0.1
  tekton-dashboard-release-readonly:
  - apiVersion: v2
    appVersion: 0.28.0
    created: "2022-07-30T10:04:17.804006828+02:00"
    description: A Helm chart for Kubernetes
    digest: f133de8b8da7a9a74162a2951921d710097392a4c188b649068a452b98de82a7
    name: tekton-dashboard-release-readonly
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tekton-dashboard-release-readonly-0.0.1.tgz
    version: 0.0.1
  the_independent_friend_de:
  - apiVersion: v2
    appVersion: 4.4.2
    created: "2022-07-30T10:04:17.804484063+02:00"
    description: Install the website the-independent-friend.de
    digest: 7b8a66d291529a3e740706d5e8161f3d8b7fa495937016932ce06caab68300e8
    name: the_independent_friend_de
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/the_independent_friend_de-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 4.4.2
    created: "2022-07-30T10:04:17.804311459+02:00"
    description: Install the website the-independent-friend.de
    digest: 28aa247a3864bc8367790d3400c6371f20ef6c0519147919b1b3ac2b27ae6fd6
    name: the_independent_friend_de
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/the_independent_friend_de-0.1.0.tgz
    version: 0.1.0
  tls_routing:
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2022-07-30T10:04:17.805335742+02:00"
    description: A Helm chart for Kubernetes
    digest: 9207a031ad554c1f33b7e87521adcd660297f050fc55de80b1decef652fe64d5
    name: tls_routing
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tls_routing-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2022-07-30T10:04:17.805146124+02:00"
    description: A Helm chart for Kubernetes
    digest: 94b287dafec8f2d0aa1ef97c06069b6a9020c88f498fa87d028c62fc3610eb1f
    name: tls_routing
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tls_routing-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2022-07-30T10:04:17.804853443+02:00"
    description: A Helm chart for Kubernetes
    digest: 4fd4884a39e52c57834a00e142ed352162ef8223e6359d7543def5a37f84907f
    name: tls_routing
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tls_routing-0.1.1.tgz
    version: 0.1.1
generated: "2022-07-30T10:04:17.801737051+02:00"
