apiVersion: v1
entries:
  tekton:
  - apiVersion: v2
    appVersion: 0.37.2-latest
    created: "2022-07-24T12:56:13.941083802+02:00"
    description: A Helm chart for Kubernetes
    digest: e5fcd2b05a21aeb431ba745349749c62a6906133aa43ffa7683b21b132416991
    name: tekton
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tekton-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.37.2
    created: "2022-07-24T12:56:13.939632901+02:00"
    description: A Helm chart for Kubernetes
    digest: 6d940f10a17b7848ab21626976313a5af6efe3a992c23a50684973a48b3ab4b1
    name: tekton
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tekton-0.0.1.tgz
    version: 0.0.1
  the_independent_friend_de:
  - apiVersion: v2
    appVersion: 4.4.2
    created: "2022-07-24T12:56:13.941655517+02:00"
    description: Install the website the-independent-friend.de
    digest: 14bcc03e0313c3eac955a3f1431b14d90ea3e4a529ae0ec9690d740fa4a84969
    name: the_independent_friend_de
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/the_independent_friend_de-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 4.4.2
    created: "2022-07-24T12:56:13.94142455+02:00"
    description: Install the website the-independent-friend.de
    digest: 28aa247a3864bc8367790d3400c6371f20ef6c0519147919b1b3ac2b27ae6fd6
    name: the_independent_friend_de
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/the_independent_friend_de-0.1.0.tgz
    version: 0.1.0
  tls_routing:
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2022-07-24T12:56:13.94248657+02:00"
    description: A Helm chart for Kubernetes
    digest: 17eb6049938f1e90e66c62d8dc743e4562cd98d385bffe55017ab12c6921d5f7
    name: tls_routing
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tls_routing-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2022-07-24T12:56:13.942250365+02:00"
    description: A Helm chart for Kubernetes
    digest: 94b287dafec8f2d0aa1ef97c06069b6a9020c88f498fa87d028c62fc3610eb1f
    name: tls_routing
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tls_routing-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2022-07-24T12:56:13.941997713+02:00"
    description: A Helm chart for Kubernetes
    digest: 4fd4884a39e52c57834a00e142ed352162ef8223e6359d7543def5a37f84907f
    name: tls_routing
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tls_routing-0.1.1.tgz
    version: 0.1.1
generated: "2022-07-24T12:56:13.938772854+02:00"
