apiVersion: v1
entries:
  tekton:
  - apiVersion: v2
    appVersion: 0.37.2
    created: "2022-08-06T12:09:25.77481396+02:00"
    description: A Helm chart for Kubernete
    digest: 81e29648a7edadbcdb695e999ff83e7f5f89c8cc2e80571f9e1d6cd3f5775032
    name: tekton
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tekton-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 0.37.2-latest
    created: "2022-08-06T12:09:25.774295314+02:00"
    description: A Helm chart for Kubernetes
    digest: e5fcd2b05a21aeb431ba745349749c62a6906133aa43ffa7683b21b132416991
    name: tekton
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tekton-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.37.2
    created: "2022-08-06T12:09:25.773548434+02:00"
    description: A Helm chart for Kubernetes
    digest: 6d940f10a17b7848ab21626976313a5af6efe3a992c23a50684973a48b3ab4b1
    name: tekton
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tekton-0.0.1.tgz
    version: 0.0.1
  tekton-ci-cd:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-08-06T12:09:25.776523632+02:00"
    description: Automatisation of ci/cd tasks
    digest: 99963c6e434a076f7dafdc3c17abd1242a14a4211598769e74a43380b074c123
    name: tekton-ci-cd
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tekton-ci-cd-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-08-06T12:09:25.776073232+02:00"
    description: Automatisation of ci/cd tasks
    digest: 75ca0ba61b1e9459cf470765b591c737dac2729dfedf189b82960471ee7d8f7d
    name: tekton-ci-cd
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tekton-ci-cd-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2022-08-06T12:09:25.775374894+02:00"
    description: Automatisation of ci/cd tasks
    digest: 2533a86043f841108a8e711cad68e8390380c4f3b0c130ee3122a72dbb99714a
    name: tekton-ci-cd
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tekton-ci-cd-0.0.1.tgz
    version: 0.0.1
  tekton_dashboard_release_readonly:
  - apiVersion: v2
    appVersion: 0.28.0
    created: "2022-08-06T12:09:25.777043818+02:00"
    description: A dashbord for Tekton
    digest: 75d0115ea6b36d61a6699760b204237bb6493d20f08af63e1dc44703f29509a8
    name: tekton_dashboard_release_readonly
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tekton_dashboard_release_readonly-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v2
    appVersion: 0.28.0
    created: "2022-08-06T12:09:25.77684368+02:00"
    description: A Helm chart for Kubernetes
    digest: 3b19255e3acdd9444af51d6cd57726396b59413c03b8fadd9d2a237338c8c55f
    name: tekton_dashboard_release_readonly
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tekton_dashboard_release_readonly-0.0.1.tgz
    version: 0.0.1
  tekton_task_git-clone:
  - apiVersion: v2
    appVersion: 0.6.0
    created: "2022-08-06T12:09:25.777503028+02:00"
    description: 'A Helm chart for installing Tekton task git-clone See: https://hub.tekton.dev/tekton/task/git-clone '
    digest: d8d640d94a9d806a0cfc1795040eb1b4085020084a6d0fd522324db83b8fd99a
    name: tekton_task_git-clone
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tekton_task_git-clone-0.0.1.tgz
    version: 0.0.1
  the_independent_friend_de:
  - apiVersion: v2
    appVersion: 4.4.3
    created: "2022-08-06T12:09:25.778465758+02:00"
    description: Install the website the-independent-friend.de
    digest: 6d0b6023924fb19621c7463a977db1b5668ce35d6d892af938a149ede6309035
    name: the_independent_friend_de
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/the_independent_friend_de-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 4.4.2
    created: "2022-08-06T12:09:25.778211905+02:00"
    description: Install the website the-independent-friend.de
    digest: 28aa247a3864bc8367790d3400c6371f20ef6c0519147919b1b3ac2b27ae6fd6
    name: the_independent_friend_de
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/the_independent_friend_de-0.1.0.tgz
    version: 0.1.0
  tls_routing:
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2022-08-06T12:09:25.780352652+02:00"
    description: A Helm chart for Kubernetes
    digest: caf02be4fd5e021fe02d34248c8770fc0ba3543de6c9d02b1aee0296316b8008
    name: tls_routing
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tls_routing-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2022-08-06T12:09:25.779526672+02:00"
    description: A Helm chart for Kubernetes
    digest: 94b287dafec8f2d0aa1ef97c06069b6a9020c88f498fa87d028c62fc3610eb1f
    name: tls_routing
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tls_routing-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2022-08-06T12:09:25.779212091+02:00"
    description: A Helm chart for Kubernetes
    digest: 4fd4884a39e52c57834a00e142ed352162ef8223e6359d7543def5a37f84907f
    name: tls_routing
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tls_routing-0.1.1.tgz
    version: 0.1.1
generated: "2022-08-06T12:09:25.772326147+02:00"
