apiVersion: v1
entries:
  the_independent_friend_de:
  - apiVersion: v2
    appVersion: 4.4.2
    created: "2022-07-24T09:30:11.966763592+02:00"
    description: Install the website the-independent-friend.de
    digest: a364b4b54cb81b07c77025050c9f8d1a05a957ad8dd12a466f8fdd8dd51ed93b
    name: the_independent_friend_de
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/the_independent_friend_de-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 4.4.2
    created: "2022-07-24T09:30:11.966425758+02:00"
    description: Install the website the-independent-friend.de
    digest: 28aa247a3864bc8367790d3400c6371f20ef6c0519147919b1b3ac2b27ae6fd6
    name: the_independent_friend_de
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/the_independent_friend_de-0.1.0.tgz
    version: 0.1.0
  tls_routing:
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2022-07-24T09:30:11.967491997+02:00"
    description: A Helm chart for Kubernetes
    digest: dbb48659f3c14a41f11e5a5958887c31d41ea0b8890d37aba83200ed60503d12
    name: tls_routing
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tls_routing-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2022-07-24T09:30:11.967218773+02:00"
    description: A Helm chart for Kubernetes
    digest: 94b287dafec8f2d0aa1ef97c06069b6a9020c88f498fa87d028c62fc3610eb1f
    name: tls_routing
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tls_routing-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2022-07-24T09:30:11.967014372+02:00"
    description: A Helm chart for Kubernetes
    digest: 4fd4884a39e52c57834a00e142ed352162ef8223e6359d7543def5a37f84907f
    name: tls_routing
    type: application
    urls:
    - https://olafradicke.github.io/own_dog_food/helm/charts/tls_routing-0.1.1.tgz
    version: 0.1.1
generated: "2022-07-24T09:30:11.966036983+02:00"
