creation_rules:
    - path_regex:  .*\.sops$
      hc_vault_transit_uri: "http://vault-server.vault:8200/v1/sops/keys/default"
    - path_regex:  \.tf\.sops$
      hc_vault_transit_uri: "http://vault-server.vault:8200/v1/sops/keys/default"
    - path_regex: \.test\.tf.sops$
      hc_vault_transit_uri: "http://vault-server.vault:8200/v1/sops/keys/env-test"
    - path_regex: \.prod\.yaml$
      hc_vault_transit_uri: "http://vault-server.vault:8200/v1/sops/keys/env-prod"
