# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: vault-server
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   destination:
#     # namespace: s3-storageclass
#     namespace: vault-server
#     server: https://kubernetes.default.svc
#   project: vault-server
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#       allowEmpty: true
#     syncOptions:
#       - CreateNamespace=true
#   source:
#     path: argocd-app-of-apps/cluster/irish-sea/vault-server/manifests
#     repoURL: https://github.com/OlafRadicke/own_dog_food.git
#     targetRevision: HEAD
#     directory:
#       recurse: true
#       # include: '*.argo.yaml'


