---

apiVersion:                 v1
kind:                       PersistentVolume
metadata:
  name:                     local-pv
spec:
  capacity:
    storage:                500Mi
  volumeMode:               Filesystem
  accessModes:
    -                       ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName:         local-storage
  local:
    path:                   /srv/k8s-pvc
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key:              kubernetes.io/hostname
          operator:         In
          values:
          -                 atlantic-ocean

---

kind:                       StorageClass
apiVersion:                 storage.k8s.io/v1
metadata:
  name:                     local-storage
provisioner:                kubernetes.io/no-provisioner
volumeBindingMode:          WaitForFirstConsumer