---

- name: Enable auto upgrade on Fedora
  when: ansible_facts['distribution'] == 'Fedora'
  block:
  - name: Install python3-pip with dnf
    ansible.builtin.dnf:
      name: python3-pip
      state: present


- name: Enable auto upgrade on Unbutu
  when: ansible_facts['distribution'] == 'Ubuntu'
  block:
  - name: install python3-pip
    apt:
      pkg:
      -            python3-pip

- name: install requiriert python libs
  pip:
    name:
      -           openshift
      -           pyyaml