---

- name:                         create namespace argocd-raw-apps-03
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    wait:                       "yes"
    definition:
      api_version:              v1
      kind:                     Namespace
      metadata:
        name:                   "argocd-raw-apps-03"
        labels:
          name:                 "argocd-raw-apps-03"

- name:                         add projekt from plain yaml
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ argocd_raw_apps_state }}"
    namespace:                  "argocd"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     AppProject
      metadata:
        name:                   app-of-app-03
        namespace:              argocd-raw-apps-03
        finalizers:
                                - resources-finalizer.argocd.argoproj.io
      spec:
        description:            project of apps of apps from plain yaml
        sourceRepos:
                                - '*'
        destinations:
        - namespace:            argocd-raw-apps-03
          server:               https://kubernetes.default.svc
          name:                 in-cluster
        - namespace:            argocd-raw-apps-03
          server:               https://kubernetes.default.svc
          name:                 in-cluster


- name:                         add app of app
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ argocd_raw_apps_state }}"
    namespace:                  "argocd"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   app-of-app-03
        namespace:              "argocd-raw-apps-03"
        finalizers:
                                - resources-finalizer.argocd.argoproj.io
      spec:
        project:                app-of-app-03
        syncPolicy:
          automated:
            prune:              true
          syncOptions:
                                - PruneLast=true
                                - Replace=true
                                - CreateNamespace=true
        source:
          repoURL:              https://github.com/OlafRadicke/own_dog_food.git
          targetRevision:       "{{ argocd_raw_apps_gitbranch }}"
          path:                 "{{ argocd_raw_apps_gitpath }}"
          directory:
            recurse: true
        destination:
          server:               https://kubernetes.default.svc
          namespace:            argocd-raw-apps-03
