---

- name: create mtls-client-ca
  ansible.builtin.shell: |
                  step  certificate create  \
                  "mTLS client CA"  \
                  {{ k3s_mtls_dir }}/mtls-client-ca.crt  \
                  {{ k3s_mtls_dir }}/mtls-client-ca.key  \
                  --no-password \
                  --insecure \
                  --profile leaf \
                  --san mtls-client-ca.olaf-radicke.de \
                  --not-after 2160h \
                  --kty RSA \
                  --size 4096 \
                  --ca {{ k3s_mtls_dir }}/mtls-intermediate-ca.crt  \
                  --ca-key {{ k3s_mtls_dir }}/mtls-intermediate-ca.key  \
                  --bundle \
                  --force
  args:
    creates:      "{{ k3s_mtls_dir }}/mtls-client-ca.crt"

- name: check mtls-client-ca.crt
  ansible.builtin.shell: |
                  step certificate inspect --short {{ k3s_mtls_dir }}/mtls-client-ca.crt
  register:       shell_result

- debug:
    msg:          "{{ shell_result }}"
  when:           shell_result is defined

- name: double check mtls-client-ca.crt
  ansible.builtin.shell: |
                  step certificate verify \
                    {{ k3s_mtls_dir }}/mtls-client-ca.crt \
                    --roots {{ k3s_mtls_dir }}/mtls-root-ca.crt 
  register:       shell_result

- debug:
    msg:          "{{ shell_result }}"
  when:           shell_result is defined
