---

- name: delete old secret for mTLS
  ansible.builtin.shell: |
              kubectl delete secret    \
                -n {{ k3s_namespace }} \
                mtls-ca                \
              || true
  register:   delete_result

- debug:
    msg:      "Delet result: {{ delete_result }}"
  when:       delete_result is defined

- name: create secret for mTLS
  ansible.builtin.shell: |
              kubectl create                                          \
              -n {{ k3s_namespace }}                                  \
              secret generic mtls-ca                                  \
              --from-file=tls.ca={{ k3s_mtls_dir }}/mtls-root-ca.crt

# --from-file=cacert={{ k3s_mtls_dir }}/mtls-root-ca.crt
