---

- name: delete old secret for mTLS
  ansible.builtin.shell: |
              kubectl delete secret    \
                -n {{ item }} \
                mtls-ca                \
                --wait=true            \
              || true
  register:   delete_result
  loop:      "{{ mtls_secreat_namespaces }}"

- debug:
    msg:      "Delet result: {{ delete_result }}"
  when:       delete_result is defined

- name: create secret for mTLS
  ansible.builtin.shell: |
              kubectl create                                          \
              -n {{ item }}                                  \
              secret generic mtls-ca                                  \
              --from-file=tls.ca={{ k3s_mtls_dir }}/mtls-root-ca.crt   
  loop:      "{{ mtls_secreat_namespaces }}"

