---

- name: delete old secret for pulling images
  ansible.builtin.shell: |
              kubectl delete secret mtls-ca|| true
  register:   delete_result

- debug:
    msg:      "Delet result: {{ delete_result }}"
  when:       delete_result is defined

- name: create secret for pulling images
  ansible.builtin.shell: |
              kubectl create secret generic mtls-ca \
                --from-file=mtls_ca.crt=/home/{{ ansible_user }}/private_pki/mtls_ca.crt \
                --type=kubernetes.io/tls