---

- name:                         Setup default of tls options
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ argocd_app_tif_test_state}}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               traefik.containo.us/v1alpha1
      kind:                     TLSOption
      metadata:
        name:                   default
        namespace:              default
      spec:
        clientAuth:
          clientAuthType:       RequireAndVerifyClientCert
  loop:      "{{ mtls_secreat_namespaces }}"