
apiVersion:               traefik.containo.us/v1alpha1
kind:                     Middleware
metadata:
  name:                   redirect-{{ .Values.app.name }}
  namespace:              {{ .Release.Namespace }}
spec:
  redirectScheme:
    scheme:               https
    permanent:            true
