---

ansible_host:                     65.109.129.176
ansible_user:                     "oradicke"
ansible_become:                   yes
ansible_python_interpreter:       "/usr/bin/python3"

# ---- GLOBAL ----

global_kubeconfig:                "/etc/rancher/k3s/k3s.yaml"
# debug_mode:                       True


# ---- mTLS ----

k3s_refresh_client_certificate:   false
k3s_refresh_inter_certificate:    false
# k3s_mtls_secreat_namespaces:
#   -                               "argocd-apps"
#   -                               "argocd"
#   -                               "monitoring"