apiVersion: batch/v1
kind: CronJob
metadata:
  name: alketas
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      template:
        spec:
          containers:
            - name: renew-loop
              image: olafradicke/alketas:0.6
              imagePullPolicy: IfNotPresent
              env:
                - name: VAULT_ADDR
                  value: "http://openbao.openbao:8200"
                - name: VAULT_CACERT
                  value: "/alketas/certs/root-ca.crt"
                - name: VAULT_SKIP_VERIFY
                  value: "false"
                - name: VAULT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: env-token-secret
                      key: token
                - name: VAULT_RENEW_TOKENS
                  value: "/alketas/confs/tokens.yaml"
              volumeMounts:
                - name: renew-tokens
                  mountPath: "/alketas/confs" # tokens.yaml
                  readOnly: true
                - name: root-ca
                  mountPath: "/alketas/certs" # root-ca.crt
                  readOnly: true

          restartPolicy: OnFailure
          volumes:
            - name: renew-tokens
              secret:
                secretName: renew-tokens
                optional: true
            - name: root-ca
              secret:
                secretName: root-ca
                optional: true
