apiVersion: batch/v1
kind: CronJob
metadata:
  name: alketas
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renew-loop
              image: olafradicke/alketas:0.3
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
