apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-storage-retain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: "local-storage-retain"
  # storageClassName: ""
