apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: cron-listener
spec:
  serviceAccountName: tekton-triggers-example-sa
  triggers:
    - name: cron-trig
      bindings:
      - ref: triggerbinding-hello
      template:
        ref: triggertemplate-simple
