# ---

# apiVersion: triggers.tekton.dev/v1alpha1
# kind: EventListener
# metadata:
#   name: eventlistener-github-pr
# spec:
#   serviceAccountName: tekton-triggers-example-sa
#   triggers:
#     - name: github-listener
#       interceptors:
#         - ref:
#             name: "github"
#           params:
#             # - name: "secretRef"
#             #   value:
#             #     secretName: github-interceptor-secret
#             #     secretKey: secretToken
#             - name: "eventTypes"
#               value: ["push"]
#         # - ref:
#         #     name: "cel"
#         #   params:
#         #     - name: "filter"
#         #       value: "body.action in ['opened', 'synchronize', 'reopened']"
#       bindings:
#         - ref: github-pr-binding
#       template:
#         ref: github-pr-pipeline-template

# ---
# apiVersion: triggers.tekton.dev/v1alpha1
# kind: EventListener
# metadata:
#   name: eventlistener-listener-interceptor
# spec:
#   serviceAccountName: tekton-triggers-example-sa
#   triggers:
#     - name: foo-trig
#       interceptors:
#         - webhook:
#             header:
#               - name: Foo-Trig-Header1
#                 value: string-value
#               - name: Foo-Trig-Header2
#                 value:
#                   - array-val1
#                   - array-val2
#             objectRef:
#               kind: Service
#               name: gh-validate
#               apiVersion: v1
#               namespace: default
#       bindings:
#         - ref: pipeline-binding
#       template:
#         name: pipeline-template

---

apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: eventlistener-cron-listener
spec:
  serviceAccountName: tekton-triggers-admin
  # serviceAccountName: serviceaccount-tekton-triggers
  triggers:
    - name: cron-trig
      bindings:
      - ref: triggerbinding-cron-binding
      # - name: message-binding
      #   spec:
      #     params:
      #     - name: gitrevision
      #       value: master
      #     - name: gitrepositoryurl
      #       value: https://github.com/tektoncd/triggers
      template:
        ref: triggertemplate-pipeline-template