



apiVersion:     tekton.dev/v1beta1
kind:           Task
metadata:
  name:         task-simple
spec:
  description:  Say hello.
  params:
  - name: message
    value: $(tt.params.message)
  - name: contenttype
    value: $(tt.params.contenttype)
  - name: git-revision
    value: $(tt.params.gitrevision)
  - name: git-url
    value: $(tt.params.gitrepositoryurl)
  steps:
  - name:       step-echo
    image:      alpine:latest
    script:     |
                #!/usr/bin/env sh
                echo HALLO $(params.message) $(tt.params.message)