---


apiVersion:     tekton.dev/v1beta1
kind:           Task
metadata:
  name:         task-simple
spec:
  description:  Say hello.
  # debug:
  #   breakpoint: ["onFailure"]
  params:
    - name:     firstname
      type:     string
    - name:     lastname
      type:     string
  steps:
  - name:       step-echo
    image:      alpine:latest
    # args:       ["sleep", "600"]
    command:
      - "echo"
    args:
      - "HALLO"
      - "$(params.firstname)"
      - "$(params.lastname)"
    # script:     |
    #             echo HALLO $(params.firstname) $(params.lastname)
    # script:     |
    #             #!/usr/bin/env sh
    #             echo HALLO $(params.firstname) $(params.lastname)
    #             sleep 120