---

apiVersion:     tekton.dev/v1beta1
kind:           Task
metadata:
  namespace:    "tekton-ci-cd"
  name:         show-readme
  description:  Read and display README file.
spec:
  workspaces:
  - name:       source
  steps:
  - name:       read
    image:      alpine:latest
    script:     |
                #!/usr/bin/env sh
                cat $(workspaces.source.path)/README.md
                cat $(workspaces.source.path)/helm/README.md
  - name:       chart-build
    image:      alpine/helm:latest
    script:     |
                $(workspaces.source.path)/helm/scrips/build.sh