---


apiVersion:     tekton.dev/v1beta1
kind:           Task
metadata:
  name:         task-simple
spec:
  description:  Say hello.
  params:
    - name:     firstname
      type:     string
    - name:     lastname
      type:     string
  steps:
  - name:       step-echo
    image:      alpine:latest
    args:       ["sleep", "600"]
    script:     |
                #!/usr/bin/env sh
                sleep 120
                echo HALLO $(params.firstname) $(params.lastname)
                sleep 120

  # debug:
  #   breakpoint: ["onFailure"]