



apiVersion:     tekton.dev/v1beta1
kind:           Task
metadata:
  name:         task-simple
spec:
  description:  Say hello.
  params:
  - name: message
    type: string
  - name: contenttype
    type: string
  - name: git-revision
    type: string
  - name: git-url
    type: string
  steps:
  - name:       step-echo
    image:      alpine:latest
    script:     |
                #!/usr/bin/env sh
                echo HALLO $(params.message)