apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: triggertemplate-simple
spec:
  params:
  - name: firstname
    description: The first name
    default: peter
  - name: lastname
    description: The last name
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: run-pipeline-simple
    spec:
      pipelineRef:
        name: pipeline-simple
      params:
      - name: firstname
        value: $(params.firstname)
      - name: lastname
        value: $(params.lastname)
      workspaces:
      - name: git-source
        emptyDir: {}
