apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: triggerbinding-hello
spec:
  params:
  - name: gitrevision
    value: master
  - name: gitrepositoryurl
    value: https://github.com/tektoncd/triggers
