app:
  name:       "test-the-independent-friend-de"

image:
  repository: "olafradicke/the-independent-friend-de"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag:        "4.4.3"

