---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentofu
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: opentofu
    server: https://kubernetes.default.svc
  project: opentofu
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
  source:
    path: argocd-app-of-apps/cluster/irish-sea/opentofu/manifests
    repoURL: https://github.com/OlafRadicke/own_dog_food.git
    targetRevision: HEAD
    directory:
      recurse: true
