---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: debugging-tools
  namespace: argocd
spec:
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
