---

- name: Add Grafana core helm chart
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ grafana_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   grafana-main
        namespace:              "{{ argocd_namespace }}"
      spec:
        project:                default
        syncPolicy:
          automated:
            prune:              true
          syncOptions:
          -                     PruneLast=true
          -                     Replace=true
          -                     ApplyOutOfSyncOnly=true
          # -                     CreateNamespace=true
        destination:
          server:               https://kubernetes.default.svc
          namespace:            "{{ grafana_namespace }}"
        source:
          chart:                grafana
          repoURL:              https://grafana.github.io/helm-charts
          targetRevision:       6.50.0
          helm:
            values:             |
                                {{ grafana_values | to_nice_yaml }}