---


- name: Add Grafana core helm chart
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ grafana_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   grafana-main
        namespace:              "{{ argocd_namespace }}"
      spec:
        project:                default
        syncPolicy:
          automated:
            prune:              true
          syncOptions:
          -                     PruneLast=true
          -                     Replace=true
          -                     ApplyOutOfSyncOnly=true
          # -                     CreateNamespace=true
        destination:
          server:               https://kubernetes.default.svc
          namespace:            "{{ grafana_namespace }}"
        source:
          chart:                grafana
          repoURL:              https://grafana.github.io/helm-charts
          targetRevision:       6.50.0
          helm:
            values:             |
                                securityContext:
                                  runAsUser: 472
                                  runAsGroup: 472
                                  fsGroup: 472

                                adminUser: "{{ grafana_user }}"
                                adminPassword: "{{ grafana_password }}"


  # datasources: {}
  # #  datasources.yaml:
  # #    apiVersion: 1
  # #    datasources:
  # #    - name: Prometheus
  # #      type: prometheus
  # #      url: http://prometheus-prometheus-server
  # #      access: proxy
  # #      isDefault: true
  # #    - name: CloudWatch
  # #      type: cloudwatch
  # #      access: proxy
  # #      uid: cloudwatch
  # #      editable: false
  # #      jsonData:
  # #        authType: default
  # #        defaultRegion: us-east-1