---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: pulumi-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: postgres:10.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: keycloakdb
          - name: POSTGRES_USER
            value: keycloak
          - name: POSTGRES_PASSWORD
            value: testpassword
          # envFrom:
          #   - configMapRef:
          #       name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim