---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
data:
  ca.json: |
    {
      "root": "/home/step/certs/root_ca.crt",
      "federatedRoots": null,
      "crt": "/home/step/certs/intermediate_ca.crt",
      "key": "/home/step/secrets/intermediate_ca_key",
      "address": ":8083",
      "insecureAddress": "",
      "dnsNames": ["localhost"],
      "logger": {
        "format": "text"
      },
      "db": {
        "type": "badgerv2",
        "dataSource": "/home/step/db",
        "badgerFileLoadingMode": ""
      },
      "authority": {
        "provisioners": [
          {
            "type": "JWK",
            "name": "admin",
            "key": {
              "use": "sig",
              "kty": "EC",
              "kid": "O8oZQ261LFljE1-IiHJ0SkI30C1-f32ab9g2N4x2YeI",
              "crv": "P-256",
              "alg": "ES256",
              "x": "02OsAm050qCFy8-XCUBbZ1DTROSGyeTcC36CoK1Dcyw",
              "y": "ucgoXTxVdPdBroQAimehyB7Ka4hzYSTEe9bTL9wGXsk"
            },
            "encryptedKey": "eyJhbGciOiJQQkVTMi1IUzI1NitBMTI4S1ciLCJjdHkiOiJqd2sranNvbiIsImVuYyI6IkEyNTZHQ00iLCJwMmMiOjYwMDAwMCwicDJzIjoidFh6YnVCaVZnancxOE9IZmwya2RKdyJ9.d1kqC2J1ntyKv9bCfdY5JxO3hnpwEVi5PGL-kuDjxhwdR5VcOFTKdw.4rhY-onSfcq8Ec2x.yB5DfOH6DSIrD5q1FojDXRIapZafblZZghR9kDhU-c4IGRNMPOrbMlCO1vOU_NbQzR0K8RkkujMmxuX0LhcLagYjTCWtJKH85KySZ-bX-iE_vs1Job_NGiaivgDzYrLwoLujh0IGzmU3wd42DC9YnWUU82hUntnFo1PUK5dniFXV1COqQqUZikDSRnem5Hus8zTKCKRRa8yG1a-PFxtQ7G5wfx7rJ7_ZmRIJrjXrmTswC2ICafX1QcHZpLb8FU7c5WObW0p5IBMM2nE4tWTbnV778b2clzPmj7lb5C5wqlbqt-AMk5-e_Gq82vSWkOT0K0Pg70llZnr2v4NHqFo.BEBpM0vyGETyuLiUL4RDew"
          }
        ]
      },
      "tls": {
        "cipherSuites": [
          "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
          "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        ],
        "minVersion": 1.2,
        "maxVersion": 1.3,
        "renegotiation": false
      }
    }
  defaults.json: |
    {
      "ca-url": "https://smallstep-root-ca-step-certificates.smallstep-root-ca:443",
      "ca-config": "/home/step/config/ca.json",
      "fingerprint": "0a6c41ea968bd520860b949f0dc5f865b0b11cb730c68c0878a09150cafc5dee",
      "root": "/home/step/certs/root_ca.crt"
    }
