apiVersion: v1
kind: Service
metadata:
  labels: { app: autocert }
  name: autocert
  namespace: step
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 4443
  selector: { app: autocert }
