---

apiVersion:               argoproj.io/v1alpha1
kind:                     AppProject
metadata:
  name:                   prometheus-02
  namespace:              argocd-raw-apps-03
  finalizers:
                          - resources-finalizer.argocd.argoproj.io
spec:
  description:            project of apps of apps from plain yaml
  sourceRepos:
                          - '*'
  destinations:
  - namespace:            argocd-raw-apps-03
    server:               https://kubernetes.default.svc
    name:                 in-cluster