---

apiVersion:               argoproj.io/v1alpha1
kind:                     AppProject
metadata:
  name:                   prometheus
  namespace:              argocd-raw-apps
  finalizers:
                          - resources-finalizer.argocd.argoproj.io
spec:
  description:            project of apps of apps from plain yaml
  syncPolicy:
    syncOptions:
                          - Replace=true
  sourceRepos:
                          - '*'
  destinations:
  - namespace:            argocd-raw-apps
    server:               https://kubernetes.default.svc
    name:                 in-cluster
  sourceNamespaces:
  - app-of-app
  - argocd-raw-apps