---

apiVersion:           v1
kind:                 PersistentVolume
metadata:
  name:               "prometheus-pv-main"
  namespace:          "argocd-raw-apps"
  labels:
    app:              prometheus-main
  finalizers:
                      - kubernetes.io/pv-protection
spec:
  capacity:
    storage:          10Gi
  volumeMode:         Filesystem
  accessModes:
                      - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # Delete
  storageClassName:   local-path
  local:
    path:             "/srv/k3s_pvc"/prometheus-pv-main"
  # hostPath:
  #   path: /tmp/prometheus-main-pv
  #   type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key:        kubernetes.io/hostname
          operator:   In
          values:
                      - "baltic-sea"
