---

# apiVersion:           v1
# kind:                 PersistentVolume
# metadata:
#   name:               "prometheus-pv-main"
#   namespace:          "argocd-raw-apps-03"
#   labels:
#     app:              prometheus-main
#   finalizers:
#                       - kubernetes.io/pv-protection
# spec:
#   capacity:
#     storage:          10Gi
#   volumeMode:         Filesystem
#   accessModes:
#                       - ReadWriteOnce
#   # Delete or Retain
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: local-storage
#   local:
#     path:             /srv/k3s_pvc"/prometheus-pv-main
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key:        kubernetes.io/hostname
#           operator:   In
#           values:
#                       - "baltic-sea"
