---


- name: Enable auto upgrade on Fedora
  when: ansible_facts['distribution'] == 'Fedora'
  block:

  - name: Install the latest version of dnf-automatic
    ansible.builtin.dnf:
      name: dnf-automatic
      state: present
      # state: latest

  - name: Enable a timer unit for dnf-automatic
    ansible.builtin.systemd_service:
      name: dnf-automatic.timer
      state: started
      enabled: true

  - name: configure automatic.conf
    ansible.builtin.copy:
      src:      "automatic.conf"
      dest:     "/etc/dnf/automatic.conf"
      owner:    root
      group:    root
      mode:     '0644'


- name: Enable auto upgrade on Unbutu
  when: ansible_facts['distribution'] == 'Ubuntu'
  block:

  - name: Install unattended-upgrades
    apt:
      pkg:
      -         unattended-upgrades

  - name: configure Unattended-Upgrade
    ansible.builtin.copy:
      src:      "20auto-upgrades"
      dest:     "/etc/apt/apt.conf.d/20auto-upgrades"
      owner:    root
      group:    root
      mode:     '0644'

  - name: configure Unattended-Upgrade
    ansible.builtin.copy:
      src:      "50unattended-upgrades"
      dest:     "/etc/apt/apt.conf.d/50unattended-upgrades"
      owner:    root
      group:    root
      mode:     '0644'

  - name: Enable unattended-upgrades
    ansible.builtin.systemd:
      name:     unattended-upgrades
      state:    started
      enabled:  yes