---
apiVersion: v1
kind: Service
metadata:
  name: "mona-olaf-radicke-de"
  labels:
    app: "mona-olaf-radicke-de"
spec:
  type: ClusterIP
  selector:
    app: "mona-olaf-radicke-de"
  ports:
    - targetPort: 8080
      port: 8080
