apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual-sc
  hostPath:
    path: "/srv/data"


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manual-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  storageClassName: manual-sc
  volumeName: manual-pv