apiVersion:         argoproj.io/v1alpha1
kind:               WorkflowTemplate
metadata:
  name:             git-operation
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  templates:

    - name:         git-clone
      initContainers:
        - name:     git-data
          image:    k8s.gcr.io/git-sync:v3.1.6
          args:
                    - "--one-time"
                    - "--timeout=200"
                    - "--repo={{workflow.parameters.examplePath}}"
                    - "--root=/src/clone"
                    - "--max-sync-failures=3"
                    - "--branch={{workflow.parameters.gitBranch}}"
                    # - "-depth 2"
                    # - "--ssh"
          volumeMounts:
            - name: argo-workdir
              mountPath: /src
      container:
        image:      golang:1.10
        command:    [sh, -c]
        args:
                      - |
                          pwd \
                          && ls -lah \
                          && git branch \
                          && git checkout {{workflow.parameters.gitBranch}} \
                          && git status \
                          && ls -lah terraform/examples-01
        workingDir: /src/clone
        volumeMounts:
        - name:     argo-workdir
          mountPath: /src

