---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opentofu-backend
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 500Mi
  storageClassName: local-path

