---

apiVersion:               traefik.containo.us/v1alpha1
kind:                     IngressRoute
metadata:
  name:                   quaker-kr-de-ingressroute
spec:
  entryPoints:
                          - web
  routes:
    - match:              Host(`test.quaker-kr.de`)
      kind:               Rule
      services:
        - name:           quaker-kr-de
          port:           80
      middlewares:
        - name:           redirect-https-pulumi

---

apiVersion:               traefik.containo.us/v1alpha1
kind:                     IngressRoute
metadata:
  name:                   https-quaker-kr-de-ingressroute
spec:
  entryPoints:
                          - websecure
  routes:
    # - match:              Host(`quaker-kr.de`) && PathPrefix(`/`)
    - match:              Host(`quaker-kr.de`)
      kind:               Rule
      services:
        - name:           quaker-kr-de
          port:           80
  tls:
    secretName:           quaker-kr-de

---

apiVersion:               traefik.containo.us/v1alpha1
kind:                     Middleware
metadata:
  name:                   quaker-kr-de
spec:
  redirectScheme:
    scheme:               https
    permanent:            true

---

apiVersion:               cert-manager.io/v1
kind:                     Certificate
metadata:
  name:                   quaker-kr-de
spec:
  dnsNames:
                          - quaker-kr.de
  secretName:             quaker-kr-de
  issuerRef:
    # name:                 letsencrypt-staging
    name:                 letsencrypt-production
    kind:                 ClusterIssuer