---

apiVersion:               traefik.containo.us/v1alpha1
kind:                     IngressRoute
metadata:
  name:                   https-the-independent-friend-de
spec:
  entryPoints:
                          - web
                          - websecure
  routes:
    - match:              Host(`the-independent-friend.de`)
      kind:               Rule
      middlewares:
        - name:           redirect-the-independent-friend-de
      services:
        - name:           the-independent-friend-de
          port:           80
  tls:
    secretName:           the-independent-friend-de


---

apiVersion:               traefik.containo.us/v1alpha1
kind:                     Middleware
metadata:
  name:                   redirect-the-independent-friend-de
spec:
  redirectScheme:
    scheme:               https
    permanent:            true

---

apiVersion:               cert-manager.io/v1
kind:                     Certificate
metadata:
  name:                   the-independent-friend-de
spec:
  dnsNames:
                          - the-independent-friend.de
  secretName:             the-independent-friend-de
  issuerRef:
    # name:                 letsencrypt-staging
    name:                 letsencrypt-production
    kind:                 ClusterIssuer