---
global_kubeconfig:      "/etc/rancher/k3s/k3s.yaml"
argocd_namespace:       "argocd"
prometheus_state:       "present"
prometheus_pvc_state:   "absent"
prometheus_pv_state:    "true"
prometheus_namespace:   "monitoring"
prometheus_pvc_prefix:  "prometheus-main"
prometheus_fqdn:        "prometheus.olaf-radicke.de"
prometheus_pvc_dir:     "/srv/k3s_pvc"