---

- name:                         create deployment
  kubernetes.core.k8s:
    kubeconfig:                 "{{ k3s_kubeconfig }}"
    state:                      "{{ k3s_deployment_state }}"
    namespace:                  "{{ k3s_namespace }}"
    wait:                       "yes"
    definition:
      apiVersion:               apps/v1
      kind:                     Deployment
      metadata:
        namespace:              "{{ k3s_namespace }}"
        name:                   "{{ item.name }}"
        labels:
          app:                  "{{ item.name }}"
      spec:
        selector:
          matchLabels:
            app:                "{{ item.name }}"
        template:
          metadata:
            labels:
              app:              "{{ item.name }}"
          spec:
            containers:
            - name:             "{{ item.name }}"
              image:            "{{ item.image }}"
              imagePullPolicy:  IfNotPresent
              ports:
              - containerPort:  80
            imagePullSecrets:
            - name:             regcred
  loop:                         "{{ k3s_projects }}"

- name:                         create a service object
  kubernetes.core.k8s:
    kubeconfig:                 "{{ k3s_kubeconfig }}"
    state:                      "{{ k3s_deployment_state }}"
    namespace:                  "{{ k3s_namespace }}"
    wait:                       "yes"
    definition:
      apiVersion:               v1
      kind:                     Service
      metadata:
        name:                   "{{ item.name }}"
        namespace:              "{{ k3s_namespace }}"
        labels:
          app:                  "{{ item.name }}"
      spec:
        type:                   ClusterIP
        selector:
          app:                  "{{ item.name }}"
        ports:
        - targetPort:           80
          port:                 80
  loop:                         "{{ k3s_projects }}"



