---

################ IngressRoute ################

- name: create a IngressRoute object https-the-independent-friend-de
  kubernetes.core.k8s:
    kubeconfig:                 "{{ k3s_kubeconfig }}"
    state:                      "{{ k3s_deployment_state }}"
    namespace:                  "{{ k3s_namespace }}"
    definition:
      apiVersion:               networking.k8s.io/v1
      kind:                     Ingress
      metadata:
        name:                   the-independent-friend-de
        namespace:              "{{ k3s_namespace }}"
        annotations:
            kubernetes.io/ingress.class: traefik
            cert-manager.io/cluster-issuer: letsencrypt-prod
      spec:     
        rules:
          - host: "the-independent-friend.de"
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name:  the-independent-friend-de
                      port:
                        number: 80
            https:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name:  the-independent-friend-de
                      port:
                        number: 443

          - host: "olaf-radicke-de"
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name:  olaf-radicke-de
                      port:
                        number: 80
            https:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name:  olaf-radicke-de
                      port:
                        number: 443

# - name: create a IngressRoute object olaf-radicke-de
#   kubernetes.core.k8s:
#     kubeconfig:                 "{{ k3s_kubeconfig }}"
#     state:                      "{{ k3s_deployment_state }}"
#     namespace:                  "{{ k3s_namespace }}"
#     definition:
#       apiVersion:               networking.k8s.io/v1
#       kind:                     Ingress
#       metadata:
#         name:                   olaf-radicke-de
#         namespace:              "{{ k3s_namespace }}"
#         annotations:
#             kubernetes.io/ingress.class: traefik
#             cert-manager.io/cluster-issuer: letsencrypt-prod
#       spec:     
#         rules:
#           - host: "olaf-radicke-de"
#             http:
#               paths:
#                 - path: /
#                   pathType: Prefix
#                   backend:
#                     service:
#                       name:  olaf-radicke-de
#                       port:
#                         number: 80
#             https:
#               paths:
#                 - path: /
#                   pathType: Prefix
#                   backend:
#                     service:
#                       name:  olaf-radicke-de
#                       port:
#                         number: 443