---

- name: create a Ingress object https-the-independent-friend-de
  kubernetes.core.k8s:
    kubeconfig:                 "{{ k3s_kubeconfig }}"
    state:                      "{{ k3s_deployment_state }}"
    namespace:                  "{{ k3s_namespace }}"
    definition:
      apiVersion:               networking.k8s.io/v1
      kind:                     Ingress
      metadata:
        name:                   "{{ item.name }}"
        namespace:              "{{ k3s_namespace }}"
        annotations:
            kubernetes.io/ingress.class: traefik
            cert-manager.io/cluster-issuer: letsencrypt-prod
      spec:     
        rules:
          - host:               "{{ item.fqdn }}"
            http:
              paths:
                - path:         /
                  pathType:     Prefix
                  backend:
                    service:
                      name:     "{{ item.name }}"
                      port:
                        number: 80
            https:
              paths:
                - path:         /
                  pathType:     Prefix
                  backend:
                    service:
                      name:     "{{ item.name }}"
                      port:
                        number: 443
  loop:                         "{{ k3s_projects }}"



