---

- name: configure helm chart of traefik (staging)
  kubernetes.core.k8s:
    kubeconfig:                 "{{ k3s_kubeconfig }}"
    state:                      "{{ k3s_deployment_state }}"
    namespace:                  "{{ k3s_namespace }}"
    definition:
      apiVersion:               helm.cattle.io/v1
      kind:                     HelmChartConfig
      metadata:
        name:                   traefik
        namespace:              kube-system
      spec:
        valuesContent: |-
          additionalArguments:
            - "--log.level=DEBUG"
            - "--certificatesresolvers.le.acme.email={{ k3s_acme_email }}"
            - "--certificatesresolvers.le.acme.storage=/data/acme.json"
            - "--certificatesresolvers.le.acme.tlschallenge=true"
            - "--certificatesresolvers.le.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
  when: k3s_acme_tier == "staging"


- name: configure helm chart of traefik (production)
  kubernetes.core.k8s:
    kubeconfig:                 "{{ k3s_kubeconfig }}"
    state:                      "{{ k3s_deployment_state }}"
    namespace:                  "{{ k3s_namespace }}"
    definition:
      apiVersion:               helm.cattle.io/v1
      kind:                     HelmChartConfig
      metadata:
        name:                   traefik
        namespace:              kube-system
      spec:
        valuesContent: |-
          additionalArguments:
            - "--log.level=DEBUG"
            - "--certificatesresolvers.le.acme.email={{ k3s_acme_email }}"
            - "--certificatesresolvers.le.acme.storage=/data/acme.json"
            - "--certificatesresolvers.le.acme.tlschallenge=true"
            - "--certificatesresolvers.le.acme.caServer=https://acme-v02.api.letsencrypt.org/directory"
  when: k3s_acme_tier == "production"

# - name: set TLSOption
#   kubernetes.core.k8s:
#     kubeconfig:                 "{{ k3s_kubeconfig }}"
#     state:                      "{{ k3s_deployment_state }}"
#     namespace:                  "{{ k3s_namespace }}"
#     definition:
#       apiVersion: traefik.containo.us/v1alpha1
#       kind: TLSOption
#       metadata:
#         name: tlsoptions
#         namespace: dev
#       spec:
#         minVersion: VersionTLS12
#         cipherSuites:
#           - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
#           - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
#           - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
#           - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
#           - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
#           - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
#           - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
#           - TLS_AES_256_GCM_SHA384
#           - TLS_AES_128_GCM_SHA256
#           - TLS_CHACHA20_POLY1305_SHA256
#           - TLS_FALLBACK_SCSV
#         curvePreferences:
#           - CurveP521
#           - CurveP384
#         sniStrict: false

