---

- debug:
    msg: "k3s_deployment_state: {{ k3s_deployment_state }}"

- debug:
    msg: "k3s_letsencrypt: {{ k3s_letsencrypt }}"
 
- name: create a k8s namespace testing
  kubernetes.core.k8s:
    kubeconfig:   "{{ k3s_kubeconfig }}"
    name:         "{{ k3s_namespace }}"
    api_version:  v1
    kind:         Namespace
    state:        "{{ k3s_deployment_state }}"

- name: Include task for olaf-radicke.de domain
  include_tasks: olaf-radicke-de.yaml
