---

# - name: copy kube config
#   ansible.builtin.copy:
#     src:          "/etc/rancher/k3s/k3s.yaml"
#     dest:         "/home/{{ ansible_user }}/.kube/config"
#     owner:        "{{ ansible_user }}"
#     group:        "{{ ansible_user }}"
#     mode:         '0600'
#     remote_src:   yes
 

- name: install python3-pip
  apt:
    pkg:
     -            python3-pip

- name: install requiriert python libs
  pip:
    name:
      -           openshift
      -           pyyaml

- name: create a k8s namespace testing
  kubernetes.core.k8s:
    kubeconfig:   "{{ k3s_kubeconfig }}"
    name:         "{{ k3s_namespace }}"
    api_version:  v1
    kind:         Namespace
    state:        present

- name: create deployment
  kubernetes.core.k8s:
    kubeconfig:       "{{ k3s_kubeconfig }}"
    state:            present
    namespace:        "{{ k3s_namespace }}"
    definition:
      apiVersion:     apps/v1
      kind:           Deployment
      metadata:
        namespace:    "{{ k3s_namespace }}"
        name:         nginx
        labels:
          app:        nginx
      spec:
        selector:
          matchLabels:
            app:      nginx
        template:
          metadata:
            labels:
              app:    nginx
          spec:
            containers:
            - name:   nginx
              image:  nginx:1.21
              ports:
              - containerPort: 80

- name: create a service object
  kubernetes.core.k8s:
    kubeconfig:       "{{ k3s_kubeconfig }}"
    state:            present
    namespace:        "{{ k3s_namespace }}"
    definition:
      apiVersion:     v1
      kind:           Service
      metadata:
        name:         web
        namespace:    "{{ k3s_namespace }}"
        labels:
          app:        nginx
      spec:
        type:         NodePort
        selector:
          app:        nginx
        ports:
        - protocol:   TCP
          targetPort: 80
          name:       port-80-tcp
          port:       80
          nodePort:   31111