---
 
- name: create a k8s namespace testing
  kubernetes.core.k8s:
    kubeconfig:   "{{ k3s_kubeconfig }}"
    name:         "{{ k3s_namespace }}"
    api_version:  v1
    kind:         Namespace
    state:        "{{ k3s_deployment_state }}"

# - name: Include task for olaf-radicke.de domain
#   include_tasks: olaf-radicke-de.yaml

- name: Include task for the-independent-friend.de domain
  include_tasks: the-independent-friend-de.yaml


- name: Include task for ingress
  include_tasks: ingress.yaml