---


- name: Include task for namespaces
  include_tasks: namespaces.yaml

- name: Include task for site deployment
  include_tasks: deployments.yaml

# - name: Include task for letsencrypt
#   include_tasks: letsencrypt.yaml
#   when: k3s_letsencrypt == "yes"

- name: Include task for ingress
  include_tasks: ingress.yaml
  when: k3s_native_ingress == "yes"

- name: Include task for traefik
  include_tasks: traefik.yaml
  when: k3s_traefik == "yes"