---
 
- name: create a k8s namespace testing
  kubernetes.core.k8s:
    kubeconfig:   "{{ k3s_kubeconfig }}"
    name:         "{{ k3s_namespace }}"
    api_version:  v1
    kind:         Namespace
    state:        "{{ k3s_deployment_state }}"

- name: Include task for site deployment
  include_tasks: deployments.yaml

- name: Include task for letsencrypt
  include_tasks: letsencrypt.yaml
  when: k3s_letsencrypt == "yes"

- name: Include task for ingress
  include_tasks: ingress.yaml
  when: k3s_native_ingress == "yes"

- name: Include task for traefik
  include_tasks: traefik.yaml
  when: k3s_traefik == "yes"