---

- name: create deployment
  kubernetes.core.k8s:
    kubeconfig:                 "{{ k3s_kubeconfig }}"
    state:                      "{{ k3s_deployment_state }}"
    namespace:                  "{{ k3s_namespace }}"
    wait:                       "yes"
    definition:
      apiVersion:               apps/v1
      kind:                     Deployment
      metadata:
        namespace:              "{{ k3s_namespace }}"
        name:                   test-the-independent-friend-de
        labels:
          app:                  test-the-independent-friend-de
      spec:
        selector:
          matchLabels:
            app:                test-the-independent-friend-de
        template:
          metadata:
            labels:
              app:              test-the-independent-friend-de
          spec:
            containers:
            - name:             test-the-independent-friend-de
              image:            olafradicke/olaf-radicke-de:2.3
              imagePullPolicy:  IfNotPresent
              ports:
              - containerPort:  80
            imagePullSecrets:
            - name:             regcred

- name: create a service object
  kubernetes.core.k8s:
    kubeconfig:                 "{{ k3s_kubeconfig }}"
    state:                      "{{ k3s_deployment_state }}"
    namespace:                  "{{ k3s_namespace }}"
    wait:                       "yes"
    definition:
      apiVersion:               v1
      kind:                     Service
      metadata:
        name:                   test-the-independent-friend-de
        namespace:              "{{ k3s_namespace }}"
        labels:
          app:                  test-the-independent-friend-de
      spec:
        type:                   ClusterIP
        selector:
          app:                  test-the-independent-friend-de
        ports:
        - targetPort:           80
          port:                 80



