---

- name: create deployment
  kubernetes.core.k8s:
    kubeconfig:                 "{{ k3s_kubeconfig }}"
    state:                      "{{ k3s_deployment_state }}"
    namespace:                  "{{ k3s_namespace }}"
    wait:                       "yes"
    definition:
      apiVersion:               apps/v1
      kind:                     Deployment
      metadata:
        namespace:              "{{ k3s_namespace }}"
        name:                   the-independent-friend-de
        labels:
          app:                  the-independent-friend-de
      spec:
        selector:
          matchLabels:
            app:                the-independent-friend-de
        template:
          metadata:
            labels:
              app:              the-independent-friend-de
          spec:
            containers:
            - name:             the-independent-friend-de
              image:            olafradicke/the-independent-friend-de:2
              imagePullPolicy:  IfNotPresent
              ports:
              - containerPort:  80
            imagePullSecrets:
            - name:             regcred

- name: create a service object
  kubernetes.core.k8s:
    kubeconfig:                 "{{ k3s_kubeconfig }}"
    state:                      "{{ k3s_deployment_state }}"
    namespace:                  "{{ k3s_namespace }}"
    wait:                       "yes"
    definition:
      apiVersion:               v1
      kind:                     Service
      metadata:
        name:                   the-independent-friend-de
        namespace:              "{{ k3s_namespace }}"
        labels:
          app:                  the-independent-friend-de
      spec:
        type:                   ClusterIP
        selector:
          app:                  the-independent-friend-de
        ports:
        - targetPort:           80
          port:                 80


# - name: create a service object NodePort
#   kubernetes.core.k8s:
#     kubeconfig:                 "{{ k3s_kubeconfig }}"
#     state:                      "{{ k3s_deployment_state }}"
#     namespace:                  "{{ k3s_namespace }}"
#     wait:                       "yes"
#     definition:
#       apiVersion:               v1
#       kind:                     Service
#       metadata:
#         name:                   the-independent-friend-de
#         namespace:              "{{ k3s_namespace }}"
#         labels:
#           app:                  the-independent-friend-de
#       spec:
#         type:                   NodePort
#         selector:
#           app:                  the-independent-friend-de
#         ports:
#         - targetPort:           80
#           port:                 80
#           nodePort:             30007


