---

- name: create a IngressRoute object for https
  kubernetes.core.k8s:
    kubeconfig:                 "{{ k3s_kubeconfig }}"
    state:                      "{{ k3s_deployment_state }}"
    namespace:                  "{{ k3s_namespace }}"
    definition:
      apiVersion:               traefik.containo.us/v1alpha1
      kind:                     IngressRoute
      metadata:
        name:                   https-the-independent-friend-de
        namespace:              "{{ k3s_namespace }}"
      spec:
        entryPoints:
          -                     websecure
        routes:                 "{{ k3s_routes }}"
        tls:                    {}
  when:                         k3s_letsencrypt != "yes"

- name: create a IngressRoute object for https with letsencrypt support
  kubernetes.core.k8s:
    kubeconfig:                 "{{ k3s_kubeconfig }}"
    state:                      "{{ k3s_deployment_state }}"
    namespace:                  "{{ k3s_namespace }}"
    definition:
      apiVersion:               traefik.containo.us/v1alpha1
      kind:                     IngressRoute
      metadata:
        name:                   https-the-independent-friend-de
        namespace:              "{{ k3s_namespace }}"
      spec:
        entryPoints:
          -                     websecure
        routes:                 "{{ k3s_routes }}"
        tls:
          certResolver:         le
  when:                         k3s_letsencrypt == "yes"

- name: create a Middleware object https-ingressroute
  kubernetes.core.k8s:
    kubeconfig:                 "{{ k3s_kubeconfig }}"
    state:                      "{{ k3s_deployment_state }}"
    namespace:                  "{{ k3s_namespace }}"
    definition:
      apiVersion:               traefik.containo.us/v1alpha1
      kind:                     Middleware
      metadata:
        name:                   middleware-http-to-https
        namespace:              "{{ k3s_namespace }}"
      spec:
        redirectScheme:
          scheme:               https
          permanent:            true

- name: create a IngressRoute object http-the-independent-friend-de
  kubernetes.core.k8s:
    kubeconfig:                 "{{ k3s_kubeconfig }}"
    state:                      "{{ k3s_deployment_state }}"
    namespace:                  "{{ k3s_namespace }}"
    definition:
      apiVersion:               traefik.containo.us/v1alpha1
      kind:                     IngressRoute
      metadata:
        name:                   the-independent-friend-de
        namespace:              "{{ k3s_namespace }}"
      spec:
        entryPoints:
          -                     web
        routes:                 "{{ k3s_middleware_routes }}"

