---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-storageclass
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    # namespace: s3-storageclass
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: s3-storageclass
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  source:
    path: charts/aws-mountpoint-s3-csi-driver
    repoURL: https://github.com/awslabs/mountpoint-s3-csi-driver.git
    targetRevision: v1.14.0
    helm:
      values: |
        awsAccessSecret:
          name: s3-driver-secret
          keyId: key_id
          accessKey: access_key
          sessionToken: session_token

