---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "apologie"
  labels:
    app: "apologie"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "apologie"
  template:
    metadata:
      labels:
        app: "apologie"
    spec:
      containers:
        - name: "apologie"
          image: "olafradicke/apologie:0.2.8"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
