---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smallstep-autocert
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: smallstep-autocert
    server: https://kubernetes.default.svc
  project: smallstep-autocert
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
  # source:
  #   path: install/
  #   repoURL: https://github.com/smallstep/autocert.git
  #   targetRevision: v0.20.1
  #   directory:
  #     recurse: true
  #     include: "{*autocert.yaml, *rbac.yaml}"
  source:
    path: argocd-app-of-apps/cluster/irish-sea/smallstep-autocert/manifests
    repoURL: https://github.com/OlafRadicke/own_dog_food.git
    targetRevision: HEAD
    directory:
      recurse: true
