---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: uptime-kuma
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage-uptime-kuma
  local:
    path: /srv/k8s-pvc/local-storage-uptime-kuma
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "atlantic-ocean"