---

kind:                       PersistentVolumeClaim
apiVersion:                 v1
metadata:
  name:                     local-storage-uptime-kuma
  # namespace:                uptime-kuma
spec:
  accessModes:
    -                       ReadWriteOnce
  # storageClassName:         local-storage-uptime-kuma
  storageClassName:         uptime-kuma
  resources:
    requests:
      storage:              100Mi
