---
# https://www.fadhil-blog.dev/blog/rancher-local-path-provisioner/
# sudo ls -lah /var/lib/rancher/k3s/storage

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: local-path
  storageClassName: local-storage
  resources:
    requests:
      storage: 128Mi