# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: web-user
#   labels:
#     rbac.authorization.k8s.io/aggregate-to-admin: "true"
# rules:
# - apiGroups:
#   - argoproj.io
#   resources:
#   - "*"
#   verbs:
#   - "*"