apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: web-user
  namespace: argo
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  - cronworkflows
  verbs:
  - list
  - update