---

apiVersion:               tekton.dev/v1beta1
kind:                     PipelineRun
metadata:
  namespace:              "tekton-ci-cd"
  name:                   run-pipeline
spec:
  pipelineRef:
    name:                 pipeline-clone-read
  workspaces:
  - name:                 shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
                          - ReadWriteOnce
        resources:
          requests:
            storage:      1Gi
  # - name:                 git-credentials
  #   secret:
  #     secretName:         git-credentials
  params:
  - name:                 repo-url
    value:                https://github.com/OlafRadicke/own_dog_food.git
