---

- name: Add Prometheus core helm chart
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ prometheus_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   prometheus-main
        namespace:              "{{ argocd_namespace }}"
      spec:
        project:                default
        syncPolicy:
          automated:
            prune:              true
          syncOptions:
          -                     PruneLast=true
          -                     Replace=true
          -                     ApplyOutOfSyncOnly=true
          # -                     CreateNamespace=true
        destination:
          server:               https://kubernetes.default.svc
          namespace:            "{{ prometheus_namespace }}"
        source:
          chart:                prometheus
          repoURL:              https://prometheus-community.github.io/helm-charts
          targetRevision:       15.9.1
          helm:
            values:             |
                                {{ prometheus_values | to_nice_yaml }}