
---

all:
  hosts:
    'olaf-radicke-02':
      ansible_host:               92.205.105.117
      ansible_user:               oradicke
      ansible_become:             yes
      ansible_python_interpreter: /usr/bin/python3
