
---

all:
  hosts:
    'olaf-radicke-02':
      argocd_reset:               false 
      argocd_letsencrypt:         true
      ansible_host:               92.205.105.117
      ansible_user:               "oradicke"
      ansible_become:             yes
      ansible_python_interpreter: "/usr/bin/python3"
      k3s_acme_email:             "briefkasten@olaf-radicke.de"
      k3s_namespace:              "live"
      # k3s_deployment_state:       "absent"
      # private_pki_reset:          "yes"
      k3s_acme_tier:              "production"
      mtls_secreat_namespaces:
        -                         "live"
        -                         "argocd"
        -                         "monitoring"
      k3s_projects:
        - name:                   "olaf-radicke-de"
          image:                  "olafradicke/olaf-radicke-de:2.12"
        - name:                   "the-independent-friend-de"
          image:                  "olafradicke/the-independent-friend-de:4.2.13"
        - name:                   "test-the-independent-friend-de"
          image:                  "olafradicke/the-independent-friend-de:4.2.13"
      k3s_routes:
        - match:                  Host(`olaf-radicke.de`)
          kind:                   Rule
          services:
          - name:                 olaf-radicke-de
            port:                 80
        - match:                  Host(`the-independent-friend.de`)
          kind:                   Rule
          services:
          - name:                 the-independent-friend-de
            port:                 80
      k3s_routes_mtls:
        - match:                  Host(`test.the-independent-friend.de`)
          kind:                   Rule
          services:
          - name:                 test-the-independent-friend-de
            port:                 80
          middlewares:
          - name:                 middleware-http-to-https
            namespace:            "{{ k3s_namespace }}"
      k3s_middleware_routes:      
        - match:                  Host(`olaf-radicke.de`)
          kind:                   Rule
          services:
          - name:                 olaf-radicke-de
            port:                 80
          middlewares:
          - name:                 middleware-http-to-https
            namespace:            "{{ k3s_namespace }}"
          - name:                 middleware-http-to-https
            namespace:            "{{ k3s_namespace }}"
        - match:                  Host(`the-independent-friend.de`)
          kind:                   Rule
          services:
          - name:                 the-independent-friend-de
            port:                 80
          middlewares:
          - name:                 middleware-http-to-https
            namespace:            "{{ k3s_namespace }}"