---

- name: Local operations
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name:           create a directory for client certificate download
    ansible.builtin.file:
      path:         "{{ k3s_download_dir }}"
      state:        directory

- name: Run baltic-sea
  hosts: baltic-sea
  roles:
    - os_configs
    - k3s_install
    - k8s_ansible_requirements
    - argocd
    - k3s_mtls

# - name: Run all steps
#   hosts: olaf-radicke-02
#   roles:
#     # - ping
#     - os_configs
#     # - k3s_install
#     # - k8s_ansible_requirements
#     # - k3s_deployment
#     # - argocd
#     # - argocd_apps
#     # - k3s_mtls