apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: example-forgejo
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
spec:
  pipelineSpec:
    workspaces:
      - name: source
    tasks:
      - name: clone
        taskRef:
          kind: ClusterTask
          name: git-clone # aus tektoncd/catalog
        workspaces:
          - name: output
            workspace: source
        params:
          - name: url
            value: "$(params.repo_url)"
          - name: revision
            value: "$(params.revision)"
          - name: deleteExisting
            value: "true"

      - name: echo
        runAfter: [clone]
        taskSpec:
          workspaces:
            - name: source
          steps:
            - name: say-hello
              image: alpine:3.18
              workingDir: /workspace/source
              script: |
                echo "Hello from Tekton + Forgejo"
  params:
    - name: repo_url
      value: "$(params.repository_url)" # von PaC gesetzt
    - name: revision
      value: "$(params.revision)" # von PaC gesetzt
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
