---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: uptime-kuma
    server: https://kubernetes.default.svc
  project: uptime-kuma
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
  source:
    path: argocd-app-of-apps/cluster/irish-sea/uptime-kuma/manifests
    repoURL: https://github.com/OlafRadicke/own_dog_food.git
    targetRevision: HEAD
    directory:
      recurse: true
      # include: '*.argo.yaml'
