---
{{- if .Values.cronjob.enabled }}
# apiVersion: batch/v1
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}-cron
spec:
  schedule: {{ .Values.cronjob.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}-cron
            image: {{ .Values.cronjob.image }}
            imagePullPolicy: IfNotPresent
            command: {{ .Values.cronjob.command }}
          restartPolicy: OnFailure
{{- end }}