

apiVersion:               traefik.containo.us/v1alpha1
kind:                     TLSOption
metadata:
  name:                   m-tls-options-{{ .Values.app.name }}
  namespace:              {{ .Release.Namespace }}
spec:
  minVersion:             VersionTLS12
  cipherSuites:
                          - TLS_CHACHA20_POLY1305_SHA256
                          - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
                          - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
                          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
                          - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
                          - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
                          - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
                          - TLS_FALLBACK_SCSV
  curvePreferences:
                          - CurveP521
                          - CurveP384
  sniStrict:              false
{{ if .Values.secretnames }}
  clientAuth:
    clientAuthType:       RequireAndVerifyClientCert
    secretNames:
      -                   {{ .Values.secretnames }}
{{ end }}