---

- name:                         add ArgoCD app Tekton
  kubernetes.core.k8s:
    kubeconfig:                 "{{ argocd_kubeconfig }}"
    state:                      "{{ argocd_app_prometheus_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   tekton-main
        namespace:              "{{ argocd_namespace }}"
      spec:
        project:                default
        syncPolicy:
          automated:
            prune:              true
          syncOptions:
          -                     PruneLast=true
          -                     Replace=true
        destination:
          server:               https://kubernetes.default.svc
          namespace:            tekton-pipelines
        source:
          chart:                tekton
          repoURL:              https://olafradicke.github.io/own_dog_food/helm/charts/
          targetRevision:       0.0.3


# - name:                         add Tekton routing
#   kubernetes.core.k8s:
#     kubeconfig:                 "{{ argocd_kubeconfig }}"
#     state:                      "{{ argocd_app_tif_test_state }}"
#     namespace:                  "{{ argocd_namespace }}"
#     definition:
#       apiVersion:               argoproj.io/v1alpha1
#       kind:                     Application
#       metadata:
#         name:                   tekton-routes
#         namespace:              "{{ argocd_namespace }}"
#       spec:
#         project:                default
#         syncPolicy:
#           automated:
#             prune:              true
#           syncOptions:
#           -                     PruneLast=true
#           -                     Replace=true
#         destination:
#           server:               "https://kubernetes.default.svc"
#           namespace:            tekton-pipelines
#         source:
#           chart:                tls_routing
#           repoURL:              https://olafradicke.github.io/own_dog_food/helm/charts/
#           targetRevision:       0.1.3
#           helm:
#             values: |
#                                 app:
#                                   name:         tekton-olaf-radicke-de
#                                   fqdn:         tekton.olaf-radicke.de
#                                   service:      tekton-service
#                                   service_port: 80
#                                 mtls:
#                                   enabled: true
#                                   secretnames: mtls-ca



