---

- name:                         add ArgoCD app Tekton
  kubernetes.core.k8s:
    kubeconfig:                 "{{ argocd_kubeconfig }}"
    state:                      "{{ argocd_app_tekton_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   tekton-main
        namespace:              "{{ argocd_namespace }}"
      spec:
        project:                default
        syncPolicy:
          automated:
            prune:              true
          syncOptions:
          -                     PruneLast=true
          -                     Replace=true
        destination:
          server:               https://kubernetes.default.svc
          namespace:            tekton-pipelines
        source:
          chart:                tekton
          repoURL:              https://olafradicke.github.io/own_dog_food/helm/charts/
          targetRevision:       0.0.3


- name:                         add ArgoCD app Tekton
  kubernetes.core.k8s:
    kubeconfig:                 "{{ argocd_kubeconfig }}"
    state:                      "{{ argocd_app_tekton_state }}"
    namespace:                  "tekton-cicd"
    definition:
      apiVersion:               tekton.dev/v1beta1
      kind:                     Task
      metadata:
        name:                   hello
      spec:
        steps:
          - name:               echo
            image:              alpine
            script:             |
                                #!/bin/sh
                                echo "Hello World"

- name:                         add ArgoCD app Tekton
  kubernetes.core.k8s:
    kubeconfig:                 "{{ argocd_kubeconfig }}"
    state:                      "{{ argocd_app_tekton_state }}"
    namespace:                  "tekton-cicd"
    definition:
      apiVersion:               tekton.dev/v1beta1
      kind:                     TaskRun
      metadata:
        name:                   hello-task-run
      spec:
        taskRef:
          name:                 hello

- name:                         add ArgoCD app Tekton
  kubernetes.core.k8s:
    kubeconfig:                 "{{ argocd_kubeconfig }}"
    state:                      "{{ argocd_app_tekton_state }}"
    namespace:                  "tekton-cicd"
    definition:
      apiVersion:               tekton.dev/v1beta1
      kind:                     Task
      metadata:
        name:                   goodbye-2
      spec:
        steps:
          - name:               goodbye-2
            image:              ubuntu
            script:             |
                                #!/bin/bash
                                echo "Goodbye World!" && false &&  dygwdyg                        false

- name:                         add ArgoCD app Tekton
  kubernetes.core.k8s:
    kubeconfig:                 "{{ argocd_kubeconfig }}"
    state:                      "{{ argocd_app_tekton_state }}"
    namespace:                  "tekton-cicd"
    definition:
      apiVersion:               tekton.dev/v1beta1
      kind:                     Pipeline
      metadata:
        name:                   hello-goodbye-2
      spec:
        tasks:
          - name:               hello
            taskRef:
              name:             hello
          - name:               goodbye
            runAfter:
                                - hello
            taskRef:
              name:             goodbye-2


- name:                         add ArgoCD app Tekton
  kubernetes.core.k8s:
    kubeconfig:                 "{{ argocd_kubeconfig }}"
    state:                      "{{ argocd_app_tekton_state }}"
    namespace:                  "tekton-cicd"
    definition:
      apiVersion:               tekton.dev/v1beta1
      kind:                     PipelineRun
      metadata:
        name:                   hello-goodbye-run-2
      spec:
        pipelineRef:
          name:                 hello-goodbye-2