---

- name: add ArgoCD app Prometheus main helm chart
  kubernetes.core.k8s:
    kubeconfig:                 "{{ argocd_kubeconfig }}"
    state:                      "{{ argocd_app_prometheus_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   prometheus-main
        namespace:              "{{ argocd_namespace }}"
      spec:
        project:                default
        syncPolicy:
          automated:
            prune:              true
          syncOptions:
          -                     PruneLast=true
          -                     Replace=true
        destination:
          server:               https://kubernetes.default.svc
          namespace:            monitoring
        source:
          chart:                prometheus
          repoURL:              https://prometheus-community.github.io/helm-charts
          targetRevision:       15.9.1
          helm:
            values: |
                                nameOverride: ""
                                defaultRules:
                                  create: true
                                  rules:
                                    alertmanager: true
                                    etcd: false
                                serverFiles:
                                  ## Ref: https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/
                                  alerting_rules.yml:
                                    groups:
                                      - name: Instances
                                        rules:
                                          - alert: InstanceDown
                                            expr: up == 0
                                            for: 5m
                                            labels:
                                              severity: page
                                            annotations:
                                              description: '\{\{ $labels.instance \}\} of job \{\{ $labels.job \}\} has been down for more than 5 minutes.'
                                              summary: 'Instance \{\{ $labels.instance \}\} down'


- name: add ArgoCD app Prometheus routing helm chart
  kubernetes.core.k8s:
    kubeconfig:                 "{{ argocd_kubeconfig }}"
    state:                      "{{ argocd_app_prometheus_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   prometheus-routes
        namespace:              "{{ argocd_namespace }}"
      spec:
        project:                default
        syncPolicy:
          automated:
            prune:              true
          syncOptions:
          -                     PruneLast=true
          -                     Replace=true
        destination:
          server:               "https://kubernetes.default.svc"
          namespace:            monitoring
        source:
          chart:                tls_routing
          repoURL:              https://olafradicke.github.io/own_dog_food/helm/charts/
          targetRevision:       0.1.3
          helm:
            values: |
                                app:
                                  name: prometheus
                                  fqdn: prometheus.olaf-radicke.de
                                  service: prometheus-main-server
                                mtls:
                                  enabled: true
                                  secretnames: mtls-ca


