---

- name: delete ArgoCD namespace
  kubernetes.core.k8s:
    kubeconfig:         "{{ global_kubeconfig }}"
    name:               "{{ argocd_namespace }}"
    api_version:        v1
    kind:               Namespace
    state:              absent
    wait:               yes
  when:                 argocd_reset == true

- name: create ArgoCD namespace
  kubernetes.core.k8s:
    kubeconfig:         "{{ global_kubeconfig }}"
    name:               "{{ argocd_namespace }}"
    api_version:        v1
    kind:               Namespace
    state:              present
    wait:               yes

- name: Copy ArgoCD install file
  ansible.builtin.copy:
    src:                "install.yaml"
    dest:               "/tmp/argo-insecure-install.yaml"

- name: Install ArgoCD with yaml file
  ansible.builtin.shell: kubectl apply -f /tmp/argo-insecure-install.yaml -n argocd
  register: k3s_return

- debug:
    msg: "{{ k3s_return }}"

