---

- name: Create namespaces
  kubernetes.core.k8s:
    kubeconfig: "{{ global_kubeconfig }}"
    state: "{{ argocd_state }}"
    wait: "yes"
    definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "argocd"
        labels:
          name: "argocd"

- name: Download CRD of ArgoCD
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/argoproj/argo-cd/{{ argocd_version }}/manifests/install.yaml"
    dest: /tmp/install_argocd.yaml
    mode: '0664'


- name: Install ArgoCD
  kubernetes.core.k8s:
    kubeconfig: "{{ global_kubeconfig }}"
    state: "{{ argocd_state }}"
    # wait: "yes"
    namespace: argocd
    src: /tmp/install_argocd.yaml
    # definition:
    #   api_version:              kustomize.config.k8s.io/v1beta1
    #   kind:                     Kustomization
    #   namespace:                argocd
    #   resources:
    #     - "https://raw.githubusercontent.com/argoproj/argo-cd/{{ argocd_version }}/manifests/install.yaml"

