---

- name: create a directory for docker config
  ansible.builtin.file:
    path:     "/home/{{ ansible_user }}/.docker"
    state:    directory

- name: copy docker config file 
  ansible.builtin.copy:
    src:      "~/.docker/config.json"
    dest:     "/home/{{ ansible_user }}/.docker/config.json"

- name: create secret for pulling images
  ansible.builtin.shell: |
              kubectl delete secret regcred 

- name: create secret for pulling images
  ansible.builtin.shell: |
              kubectl create secret generic regcred \
                --from-file=.dockerconfigjson=/home/{{ ansible_user }}/.docker/config.json \
                --type=kubernetes.io/dockerconfigjson