

apiVersion:               apps/v1
kind:                     Deployment
metadata:
  namespace:              {{ .Release.Namespace }}
  name:                   {{ .Values.app.name }}
  labels:
    app:                  {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app:                {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app:              {{ .Values.app.name }}
    spec:
      containers:
      - name:             {{ .Values.app.name }}
        image:            "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy:  {{ .Values.image.pullPolicy }}
        ports:
        - containerPort:  80
      imagePullSecrets:
      - name:             regcred


