---

- name:                         add ci/cd jobs
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ argocd_app_tekton_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   tekton-ci
        namespace:              "{{ argocd_namespace }}"
      spec:
        project:                default
        syncPolicy:
          automated:
            prune:              true
            allowEmpty:         true
            selfHeal:           true
          syncOptions:
          -                     PruneLast=true
          -                     Replace=true
        destination:
          server:               https://kubernetes.default.svc
          namespace:            "tekton-ci-cd"
        source:
          repoURL:              https://github.com/OlafRadicke/own_dog_food.git
          targetRevision:       develop
          path:                 argocd_app/tekton_ci