---

- name:                         add ArgoCD app GitLab runner
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ argocd_app_gitlab_runner_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   gitlab-runner
        namespace:              "{{ argocd_namespace }}"
      spec:
        project:                default
        syncPolicy:
          automated:
            prune:              true
          syncOptions:
          -                     PruneLast=true
          -                     Replace=true
        destination:
          server:               https://kubernetes.default.svc
          namespace:            tekton-pipelines
        source:
          chart:                gitlab-runner
          repoURL:              https://charts.gitlab.io
          targetRevision:       0.47.1
          helm:
            values: |
                      gitlabUrl: https://gitlab.com/
                      runnerRegistrationToken: {{ gitlab_registration_token }}
                      runnerToken:
                      runners:
                        tags:   "olaf-radicke-linux"
                        name:   "olaf-radicke"


# doku / example
# https://gitlab.com/gitlab-org/charts/gitlab-runner/blob/main/values.yaml?_gl=1%2a188afpg%2a_ga%2aMTc1NTA5NDA4NC4xNjcwMDcwNDUy%2a_ga_ENFH3X7M5Y%2aMTY3MDA3MDQ1MS4xLjEuMTY3MDA3Mjc2NC4wLjAuMA..