---

# Based on https://github.com/prometheus-community/helm-charts

- name:                         Include variable of value_prometheus.yaml
  ansible.builtin.include_vars:
    file:                       value_prometheus.yaml
    name:                       argocd_app_prometheus_values

- name: create PersistentVolume
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ argocd_app_prometheus_pvc_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: prometheus-main-pv
        namespace: monitoring
        labels:
          app: prometheus-main-pv
        finalizers:
        - kubernetes.io/pv-protection
      spec:
        capacity:
          storage: 1Gi
        accessModes:
        - ReadWriteOnce
        hostPath:
          path: /tmp/prometheus-main-pv
          type: DirectoryOrCreate
        nodeAffinity:
          required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ip-92-205-105-117.ip.secureserver.net
        persistentVolumeReclaimPolicy: Delete
        storageClassName: local-path


- name: create PersistentVolumeClaim
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ argocd_app_prometheus_pvc_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        labels:
          app: prometheus
          app.kubernetes.io/instance: prometheus-main
          chart: prometheus-15.9.1
          component: server
          release: prometheus-main
        name: prometheus-main-server
        namespace: monitoring
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path
        volumeName: prometheus-main-pv
        volumeMode: Filesystem
        selector:
          matchLabels:
            app: prometheus-main-pv


- name: add ArgoCD app Prometheus main helm chart
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ argocd_app_prometheus_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   prometheus-main
        namespace:              "{{ argocd_namespace }}"
      spec:
        project:                default
        syncPolicy:
          automated:
            prune:              true
          syncOptions:
          -                     PruneLast=true
          -                     Replace=true
        destination:
          server:               https://kubernetes.default.svc
          namespace:            monitoring
        source:
          chart:                prometheus
          repoURL:              https://prometheus-community.github.io/helm-charts
          targetRevision:       15.9.1
          helm:
            values:             |
                                {{ argocd_app_prometheus_values | to_nice_yaml }}



- name: add ArgoCD app Prometheus routing helm chart
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ argocd_app_prometheus_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   prometheus-routes
        namespace:              "{{ argocd_namespace }}"
      spec:
        project:                default
        syncPolicy:
          automated:
            prune:              true
          syncOptions:
          -                     PruneLast=true
          -                     Replace=true
        destination:
          server:               "https://kubernetes.default.svc"
          namespace:            monitoring
        source:
          chart:                tls_routing
          repoURL:              https://olafradicke.github.io/own_dog_food/helm/charts/
          targetRevision:       0.3.0
          helm:
            values: |
                                app:
                                  name: prometheus
                                  fqdn: prometheus.olaf-radicke.de
                                  service: prometheus-main-server
                                  service_port: 80
                                mtls:
                                  enabled: true
                                  secretnames: mtls-ca


