---


- name:                         add concourse helm chart
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ argocd_app_concourse_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   concourse
        namespace:              "{{ argocd_namespace }}"
      spec:
        project:                default
        syncPolicy:
          automated:
            prune:              true
          syncOptions:
          -                     PruneLast=true
          -                     Replace=true
        destination:
          server:               https://kubernetes.default.svc
          namespace:            argocd
        source:
          chart:                concourse
          repoURL:              https://concourse-charts.storage.googleapis.com/
          targetRevision:       17.0.6
          helm:
            values: |
                                concourse:
                                  web:
                                    externalUrl: https://concourse.olaf-radicke.de/
                                  auth:
                                    mainTeam:
                                      localUser: admin
                                secrets:
                                  localUsers: admin:admin



- name: add concourse routing
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ argocd_app_concourse_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   concourse-routes
        namespace:              "{{ argocd_namespace }}"
      spec:
        project:                default
        syncPolicy:
          automated:
            prune:              true
          syncOptions:
          -                     PruneLast=true
          -                     Replace=true
        destination:
          server:               "https://kubernetes.default.svc"
          namespace:            argocd
        source:
          chart:                tls_routing
          repoURL:              https://olafradicke.github.io/own_dog_food/helm/charts/
          targetRevision:       0.2.2
          helm:
            values: |
                                app:
                                  name: concourse
                                  fqdn: concourse.olaf-radicke.de
                                  service: concourse-web
                                  service_port: 8080
                                mtls:
                                  enabled: true
                                  secretnames: mtls-ca


# - name:                 add concourse example
#   kubernetes.core.k8s:
#     kubeconfig:         "{{ global_kubeconfig }}"
#     state:              "{{ argocd_deployment_state }}"
#     namespace:          "{{ argocd_namespace }}"
#     wait:               yes
#     definition:
#       apiVersion:       argoproj.io/v1alpha1
#       kind:             Workflow
#       metadata:
#         generateName:   hello-world-
#         labels:
#           workflows.argoproj.io/archive-strategy: "false"
#         annotations:
#           workflows.argoproj.io/description: |
#                         This is a simple hello world example.
#                         You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
#       spec:
#         entrypoint:     whalesay
#         templates:
#         - name:         whalesay
#           container:
#             image:      docker/whalesay:latest
#             command:    [cowsay]
#             args:       ["hello world"]