---

- name:                         add ArgoCD app cronjob
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ argocd_app_cronjob_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   custom-cronjob
        namespace:              "{{ argocd_namespace }}"
      spec:
        project:                default
        syncPolicy:
          automated:
            prune:              true
          syncOptions:
          -                     PruneLast=true
          -                     Replace=false
        destination:
          server:               https://kubernetes.default.svc
          namespace:            argocd-apps
        source:
          chart:                custom-cronjob
          repoURL:              https://olafradicke.github.io/own_dog_food/helm/charts/
          targetRevision:       0.1.0
          # helm:
            # values: |
            #           gitlabUrl: https://gitlab.com/
            #           runnerRegistrationToken: {{ gitlab_registration_token }}
            #           runnerToken:
            #           runners:
            #             tags:   "olaf-radicke-linux"
            #             name:   "olaf-radicke"

