---

- name:                         Include variable of value_prometheus.yaml
  ansible.builtin.include_vars:
    file:                       value_prometheus.yaml
    name:                       argocd_app_prometheus_values

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   annotations:
#     pv.kubernetes.io/provisioned-by: rancher.io/local-path
#   creationTimestamp: "2022-08-04T06:20:37Z"
#   finalizers:
#   - kubernetes.io/pv-protection
#   name: pvc-575fd82c-abd8-4ad3-83c1-e1dca30699ba
#   resourceVersion: "1012735"
#   uid: 8d78729c-6671-4a1d-9bb3-bea451e502df
# spec:
#   accessModes:
#   - ReadWriteOnce
#   capacity:
#     storage: 1Gi
#   claimRef:
#     apiVersion: v1
#     kind: PersistentVolumeClaim
#     name: pvc-d121bd87c7
#     namespace: tekton-ci-cd
#     resourceVersion: "1012710"
#     uid: 575fd82c-abd8-4ad3-83c1-e1dca30699ba
#   hostPath:
#     path: /var/lib/rancher/k3s/storage/pvc-575fd82c-abd8-4ad3-83c1-e1dca30699ba_tekton-ci-cd_pvc-d121bd87c7
#     type: DirectoryOrCreate
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - ip-92-205-105-117.ip.secureserver.net
#   persistentVolumeReclaimPolicy: Delete
#   storageClassName: local-path
#   volumeMode: Filesystem
# status:
#   phase: Bound

- name: create PersistentVolume
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ argocd_app_prometheus_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: prometheus-main-pv
        namespace: monitoring
        labels:
          app: prometheus-main-pv
        finalizers:
        - kubernetes.io/pv-protection
      spec:
        capacity:
          storage: 1Gi
        accessModes:
        - ReadWriteOnce
        hostPath:
          path: /tmp/prometheus-main-pv
          type: DirectoryOrCreate
        nodeAffinity:
          required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ip-92-205-105-117.ip.secureserver.net
        persistentVolumeReclaimPolicy: Delete
        storageClassName: local-path

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   annotations:
#     pv.kubernetes.io/bind-completed: "yes"
#     pv.kubernetes.io/bound-by-controller: "yes"
#     volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
#     volume.kubernetes.io/selected-node: ip-92-205-105-117.ip.secureserver.net
#     volume.kubernetes.io/storage-provisioner: rancher.io/local-path
#   creationTimestamp: "2022-08-04T06:20:33Z"
#   finalizers:
#   - kubernetes.io/pvc-protection
#   name: pvc-d121bd87c7
#   namespace: tekton-ci-cd
#   ownerReferences:
#   - apiVersion: tekton.dev/v1beta1
#     blockOwnerDeletion: true
#     controller: true
#     kind: PipelineRun
#     name: clone-read-run
#     uid: 52fd95db-cd9f-4f93-b8f1-09290e4bf625
#   resourceVersion: "1012737"
#   uid: 575fd82c-abd8-4ad3-83c1-e1dca30699ba
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: local-path
#   volumeMode: Filesystem
#   volumeName: pvc-575fd82c-abd8-4ad3-83c1-e1dca30699ba
# status:
#   accessModes:
#   - ReadWriteOnce
#   capacity:
#     storage: 1Gi
#   phase: Bound



- name: create PersistentVolumeClaim
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ argocd_app_prometheus_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        labels:
          app: prometheus
          app.kubernetes.io/instance: prometheus-main
          chart: prometheus-15.9.1
          component: server
          release: prometheus-main
        name: prometheus-main-server
        namespace: monitoring
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path
        volumeName: prometheus-main-pv
        volumeMode: Filesystem
        selector:
          matchLabels:
            app: prometheus-main-pv


- name: add ArgoCD app Prometheus main helm chart
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ argocd_app_prometheus_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   prometheus-main
        namespace:              "{{ argocd_namespace }}"
      spec:
        project:                default
        syncPolicy:
          automated:
            prune:              true
          syncOptions:
          -                     PruneLast=true
          -                     Replace=true
        destination:
          server:               https://kubernetes.default.svc
          namespace:            monitoring
        source:
          chart:                prometheus
          repoURL:              https://prometheus-community.github.io/helm-charts
          targetRevision:       15.9.1
          helm:
            values:             |
                                {{ argocd_app_prometheus_values | to_nice_yaml }}



- name: add ArgoCD app Prometheus routing helm chart
  kubernetes.core.k8s:
    kubeconfig:                 "{{ global_kubeconfig }}"
    state:                      "{{ argocd_app_prometheus_state }}"
    namespace:                  "{{ argocd_namespace }}"
    definition:
      apiVersion:               argoproj.io/v1alpha1
      kind:                     Application
      metadata:
        name:                   prometheus-routes
        namespace:              "{{ argocd_namespace }}"
      spec:
        project:                default
        syncPolicy:
          automated:
            prune:              true
          syncOptions:
          -                     PruneLast=true
          -                     Replace=true
        destination:
          server:               "https://kubernetes.default.svc"
          namespace:            monitoring
        source:
          chart:                tls_routing
          repoURL:              https://olafradicke.github.io/own_dog_food/helm/charts/
          targetRevision:       0.2.0
          helm:
            values: |
                                app:
                                  name: prometheus
                                  fqdn: prometheus.olaf-radicke.de
                                  service: prometheus-main-server
                                  service_port: 80
                                mtls:
                                  enabled: true
                                  secretnames: mtls-ca


