---

# A pod for debogging

apiVersion:                 apps/v1
kind:                       Deployment
metadata:
  name:                     uptime-kuma
  namespace:                pulumi-apps
spec:
  replicas:                 1
  selector:
    matchLabels:
      app:                  uptime-kuma
  template:
    metadata:
      labels:
        app:                uptime-kuma
    spec:
      containers:
        - name:             uptime-kuma
          image:            louislam/uptime-kuma:1
          imagePullPolicy:  "IfNotPresent"
          resources:
            requests:
              memory:       "64Mi"
              cpu:          "250m"
            limits:
              memory:       "128Mi"
              cpu:          "500m"
          ports:
            - containerPort: 3001
          env:
          - name:           LANG
            value:          de_DE
          volumeMounts:
            - name:         uptime-kuma-app-data
              mountPath:    /app/data
      volumes:
        - name:           uptime-kuma-app-data
          persistentVolumeClaim:
            claimName:    pvc-uptime-kuma

---

kind:                       PersistentVolumeClaim
apiVersion:                 v1
metadata:
  name:                     pvc-uptime-kuma
  namespace:                pulumi-apps
spec:
  accessModes:
    -                       ReadWriteOnce
  storageClassName:         local-storage
  resources:
    requests:
      storage:              100Mi


---


apiVersion:                 v1
kind:                       PersistentVolume
metadata:
  name:                     local-pv
spec:
  capacity:
    storage:                500Mi
  volumeMode:               Filesystem
  accessModes:
    -                       ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName:         local-storage
  local:
    path:                   /srv/k8s-pvc
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key:              kubernetes.io/hostname
          operator:         In
          values:
          -                 atlantic-ocean

---

kind:                       StorageClass
apiVersion:                 storage.k8s.io/v1
metadata:
  name:                     local-storage
provisioner:                kubernetes.io/no-provisioner
volumeBindingMode:          WaitForFirstConsumer