---

apiVersion:                 v1
kind:                       Service
metadata:
  name:                     uptime-kuma
spec:
  selector:
    app.kubernetes.io/name: uptime-kuma
  ports:
    - protocol:             TCP
      port:                 80
      targetPort:           web-ui
      type:                 ClusterIP