---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-retain
  labels:
    type: local
spec:
  storageClassName: local-storage-retain
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /srv/k8s-pvc-retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - atlantic-ocean
